Level Persistence for Design system for game state persistence #48
Small-Loan-Studio/TGO pull request #108
Opened 2024-11-13 03:47 UTC by Cherve3

Adding the persistence to any levels that are visited while playing. Currently the levels we have are in the `res://ZZ_Scratch/GreyboxingTools/` folder. There is a TODO in `Driver.gd` to replace a const for the official place for levels in the future. I touched the BadLevelA and B to for a change on the portals to a new level. Instead of using the levels location just the level name is required. I figured this would be easier since levels would most likely have distinct names and be easier to remember when we have the official levels. Left some unused functions in SerializationManager I think i will be using them still but they will be removed if I don't later on.

In Driver.gd I was getting an error in Rider for previously line 23 which is line 28 now, Returns a type [Object] which do not match function's [Driver]. It didn't break anything but it was annoying to see all the time for me and adding the `as Driver` at the end is all it needed to stop yelling at me.

The saved levels currently will always be accessible in the user folder here: 
C:\Users\\[_username_]\AppData\Roaming\Godot\app_userdata\TGO\save
Godot shorthand is `user://save/`
This is the default location up to the TGO directory. Anything after is created in `SerializationManager.gd`

2024-11-15 10:58 UTC, this-is-envy requested changes
Couple of concerns and a "how do we plan" question. But broadly this looks super solid and I think it's just tweaks away from merging.

### The concerns:
I think you might be missing some commits on this PR

When I try to run this without an autoload_scene set on Driver it fails bc of the signal/handler parameter mismatch.

When I _do_ have an autoload_scene it fails because level_name gets set in level_setup which doesn't happen until `load_level` is being called after this which requires level_name

```
print("Using level path: " + LEVEL_FILE_PATH + target_level_name + ".tscn")
load_level = load(LEVEL_FILE_PATH + target_level_name + ".tscn")
```

output of that snippet is

```
Target Level Name: LevelBase
Using level path: res://ZZ_Scratch/GreyboxingTools/LevelBase.tscn
Loading non-persisting level
```

### How do we...

What is the plan for loading and saving games. Right now this looks like it works pretty seamlessly with a single save file. How do you imagine us structuring things to manage 5 save slots or whatever and selecting one that we want to restore.

Or updating the game state as we move around but not overwriting the last time that the player chose to record progress?

2024-11-15 10:58 UTC, this-is-envy commented on Scripts/Components/LevelBase.gd
> +var level_name: String = name
What do you imagine the benefit is for having a level name set vs using the filename or path relative to whatever base we have?

2024-11-15 10:58 UTC, this-is-envy commented on Scripts/Driver.gd
> -func request_debug_load(path: String) -> void:
This is called bound to Driver.tscn's `OverlayManager / MenuManager / DebugMenu.request_load(path: String`. Removing the parameter breaks the call chain and the debug menu. Not a huge deal and we're likely to migrate away soon but also a pretty easy fix since it's pulling a path in which can be directly reformed into a level name

2024-11-15 10:58 UTC, this-is-envy commented on Scripts/Driver.gd
>  	# first add the new level
update comment / move to the location where we're actually adding the new level to _world

2024-11-15 10:58 UTC, this-is-envy commented on Scripts/Driver.gd
> +		load_level = load(LEVEL_FILE_PATH + target_level_name + ".tscn")
Because the level name / file path is deeply tied to how the SerializationManager works what do you think about moving the name <-> path code into a static method on SerializationManager (or Utils perhaps?) e.g.

```
class_name SerializationManager

const LEVEL_FILE_PATH: String = "res://ZZ_Scratch/GreyboxingTools/"

static func level_name_to_path(level_name: String, base: String = LEVEL_FILE_PATH) -> String:
   ...
```

2024-11-15 10:58 UTC, this-is-envy commented on Scripts/SerializationManager.gd
> +		printerr("Could not create directory, Error: ", error)
for the time being let's make this an `assert(false, "Could not create...")` so it's obvious when it fails.

Also, this error always reporst that it couldn't create the directory even if it succeeds because you're not checking the error code

2024-11-15 10:58 UTC, this-is-envy commented on Scripts/SerializationManager.gd
> +@onready var _persistent_levels: Dictionary = {}
rm `@onready` -- it doesn't buy you much in this case because you're not trying to resolve anything that's hanging off a scene tree; just go ahead and let it.

also, can you add some obnoxious comments describing the structure of what gets stuck in this dictionary similar to [this from ObjectsHelper](https://github.com/Small-Loan-Studio/TGO/blob/tgo_dev/addons_tgo/greyboxing/UI/ObjectsHelper.gd#L27-L34)

```
## Stores a collection of data for each helper.
##   Map[String, [Control, Control, Callable]].
##
## Key: object type id
## Value[0]: The button that activates an object detail config
## Value[1]: A container with any configuration necessary for the object config
## Value[2]: Callable that resets the configuration back to a default state
var _object_types: Dictionary = {}
```

2024-11-15 10:58 UTC, this-is-envy commented on Scripts/SerializationManager.gd
> +	var file_path: String = SAVE_FILE_PATH + level.level_name + LEVEL_EXTENSION_NAME
Similar comment as elsewhere -- because we have multiple places where we need to go to/from level names to paths we should try to put those in a central location instead of letting it spread out across the codebase.

Goal here is that if we ever want to change the method we handle conversion (I expect we will) we only need to do it in a single location.

2024-11-15 10:58 UTC, this-is-envy commented on Scripts/SerializationManager.gd
> +			"Error saving previous level: ",
you dropped the error code from the output

2024-11-15 10:58 UTC, this-is-envy commented on Scripts/SerializationManager.gd
> +	if error:
let's be explicit here: `if error != OK`

2024-11-15 10:58 UTC, this-is-envy commented on ZZ_Scratch/GreyboxingTools/BadLevelA.gd
> +	level_name = get_scene_file_path().get_file().get_basename()
I believe that we'll probably end up wanting more than the basename -- e.g. I expect we'll have stuff like: `Levels/ActOne/ManorHouse.tscn` and ``Levels/ActTwo/ManorHouse.tscn` and so we'll need to somehow account for the directory structure beyond some base

(this is always why I'm thinking we probably want to centralize the path<->name stuff)

2024-11-15 10:58 UTC, this-is-envy commented on ZZ_Scratch/GreyboxingTools/BadLevelA.gd
>  func level_setup() -> void:
because it's likely that the level name mapping will be automated we should probably put this in `LevelBase._ready` or `LevelBase._enter_tree` so that each level doesn't have to add this same boilerplate.

Maybe poke around and see if you can do it in the constructor `_init()` and chain up to the Node's with `super()`

2024-11-15 14:02 UTC, Cherve3 commented
> Couple of concerns and a "how do we plan" question. But broadly this looks super solid and I think it's just tweaks away from merging.
> 
> ### The concerns:
> I think you might be missing some commits on this PR
> 
> When I try to run this without an autoload_scene set on Driver it fails bc of the signal/handler parameter mismatch.
> 
> When I _do_ have an autoload_scene it fails because level_name gets set in level_setup which doesn't happen until `load_level` is being called after this which requires level_name
> 
> ```
> print("Using level path: " + LEVEL_FILE_PATH + target_level_name + ".tscn")
> load_level = load(LEVEL_FILE_PATH + target_level_name + ".tscn")
> ```
> 
> output of that snippet is
> 
> ```
> Target Level Name: LevelBase
> Using level path: res://ZZ_Scratch/GreyboxingTools/LevelBase.tscn
> Loading non-persisting level
> ```
Nice catches, I don't think I am missing anything regarding this but it is possible because I stashed some work before I did the PR. I was a bit confused on how that first level gets called so I didn't try to mess with it too much. Just made sure the persistence operates. I felt it didn't need too much attention for this becuase I assume a lot of this will be changing. My thoughts were we probably won't have a button that immediately loads the first level for a new game there will some story or cutscene in between maybe even menus that will change how this operates.

2024-11-15 14:26 UTC, Cherve3 commented
> ### How do we...
> What is the plan for loading and saving games. Right now this looks like it works pretty seamlessly with a single save file. How do you imagine us structuring things to manage 5 save slots or whatever and selecting one that we want to restore.
> 
> Or updating the game state as we move around but not overwriting the last time that the player chose to record progress?

I mentioned I was trying to get the inventory saving but I put that on hold since I am leaning towards that being saved as a json file but I have to look it over and see if that will work well along with learning hands on how saving json works. I shifted to focusing on saving and loading the levels. I have saving working for levels and the preparations in the `SerializationManager` to also save inventory and the player. I was going to try and get the loading functioning next. 

It maybe overkill but I figured out how to package everything into a zip file and then rename it to TGO.sav . To accommodate multiple saves we can scan the folder for any .sav files and be able to load them. There is a couple things I am unsure about. 

1. we will probably want to access some data of the save file like a name, image of the screen the save happened, etc. I was thinking maybe creating a json or txt file with this information that would be created during the save process.

2. There needs to be a way to know what level the player saved on last to make sure that is the level that is loaded. This could also be included in the txt file mentioned in the first point but I am still thinking about if there is a better way.

The new work of this is on this branch I didn't know if I should wait to clear this pr out and work on a new branch when this gets merged or I continue working as normal. I could commit what I have so far while including your other changes mentioned.

2024-11-15 14:29 UTC, Cherve3 commented on Scripts/Driver.gd
> -func request_debug_load(path: String) -> void:
I removed the path because the linter didn't like that it wasn't being used but I noticed the issue of removing it when I continued working so right now. I added it back for now but the linter won't like it unless its removed or I use it

2024-11-15 14:37 UTC, Cherve3 commented on Scripts/Components/LevelBase.gd
> +var level_name: String = name
I was imagining it would be easier for the level designers to just put the level name they wanted to go to instead of looking for the level in the resources to copy the location. I personally wanted to avoid doing string manipulation to get the level name from the string. The location where the levels are being loaded from is dynamic but what stays the same is the level name so that is more important to know in my opinion. If you have opposing thoughts on it I would be open to hearing them. We could use this as a display name in game instead of the internal name to load the levels if that makes it more useful.

2024-11-15 14:41 UTC, Cherve3 commented on Scripts/Driver.gd
> +		load_level = load(LEVEL_FILE_PATH + target_level_name + ".tscn")
I like that, something like this will make it cleaner. It has been getting a bit confusing looking at all the paths 🤣

2024-11-15 18:10 UTC, this-is-envy commented on Scripts/Driver.gd
> -func request_debug_load(path: String) -> void:
if you prefix the variable with `_` it will indicate to the linter that this is a known-unused variable, i.e., `func request_debug_load(_path: String) -> void`

2024-11-15 18:11 UTC, this-is-envy commented on Scripts/Driver.gd
> +		load_level = load(LEVEL_FILE_PATH + target_level_name + ".tscn")
It also makes it a bit more tractable to do string manipulation on the path if needed because it's all constrained to two locations 😀

2024-11-15 21:52 UTC, this-is-envy commented on Scripts/Components/LevelBase.gd
> +var level_name: String = name
My primary concern is around name collision -- I think I mention it elsewhere but I can easily imagine multiple versions of the same map that have been dropped into different directories.

In part we could arrive there so that we can have two `ManorHouse.tscn` files that are used at various points in the game but also we might just do it to provide some structure to the file system as like a way to let things be orderly especially as we start segmenting into acts post-ep1.

2024-11-15 22:03 UTC, this-is-envy commented
> > I think you might be missing some commits on this PR
> > ...
> 
> ...I don't think I am missing anything regarding this but it is possible because I stashed some work before I did the PR. I was a bit confused on how that first level gets called so I didn't try to mess with it too much. Just made sure the persistence operates. 

Eh, the reason I thought there might be missing commits was because when I ran it I couldn't get any levels to load due to the signal / `request_debug_load` parameter thing causing errors. I'm willing to bet what actually happened is that you saw the linting error, fixed that, and didn't think to recheck loadability since it wasn't really changing any code functionality.

> I felt it didn't need too much attention for this becuase I assume a lot of this will be changing. My thoughts were we probably won't have a button that immediately loads the first level for a new game there will some story or cutscene in between maybe even menus that will change how this operates.

Broadly that's true but we also can't break the ability to load directly into levels while designers are working / until we get the menu system in place. I think as built rn the only level it can load is BadLevelA since that's hard coded as FIRST_LEVEL_NAME and the callback is discarding the path that's coming into request_debug_load.

We need to ensure that, at least, the autoload_scene path continues to work which (I think?) is busted at the moment as described in [the concerns section](https://github.com/Small-Loan-Studio/TGO/pull/108#issuecomment-2478916165)

2024-11-15 23:43 UTC, this-is-envy commented
> > ### How do we...
> > What is the plan for loading and saving games...
>
> I mentioned I was trying to get the inventory saving but I put that on hold since I am leaning towards that being saved as a json file but I have to look it over and see if that will work well along with learning hands on how saving json works. I shifted to focusing on saving and loading the levels. I have saving working for levels and the preparations in the `SerializationManager` to also save inventory and the player. I was going to try and get the loading functioning next.
> 
> It maybe overkill but ... <snip great ideas> 

Haha :sickos:. Yes I'm extremely on board with all your thoughts about how to aggregate everything into a single save file etc. And also that we'll probably need some non-compressed metadata. I don't have a solution off hand but I agree that's where we should eventually end up (In a lot of languages you can mount a zip file as a readable file system so we might be able to pull an impl from [C# stdlib](https://learn.microsoft.com/en-us/dotnet/api/system.io.compression.ziparchiveentry?view=net-8.0))

That said my question was more along the lines of:

- your SerializationManager currently hardcodes a serialization path root
- any time you update the version of a level it overwrites the version of that level in the fixed location
- any time you unload a level it updates the level 

so by my understanding let's say you have a saved game. When you start the game and enter a level it'll see that there is a non-default version of the level to use and grab it.

You then leave the level it will persist any changes you've made back to disk.

Uh oh, you realize that you've fucked up and pushed a block where you didn't mean to causing a soft lock let's quit the game and reload...

But because we only have one fixed path where saves go that broken level state is now persisted to disk even though the player didn't want to save.

This is a very specific example but the same holds true if we want to have multiple save slots -- because we hard code the path where levels go and everything hangs off that we start getting collisions when we have multiple versions of a level we need to track at different states.

❗ And to be clear we don't need to solve this now -- but we should have a plan to do so so that we know that this solution has a path to evolve into a more general one that meets all the needs we'll eventually have. (I'm pretty sure I see one but I don't want to bias your take -- the last time I had an idea about saving state and let you run free yours was way better / easier to deal with)

2024-11-24 21:07 UTC, this-is-envy reviewed
I'm trying to wrap my head around update_level wiring and if I have any thoughts about that -- a handful of kind of nit-picky stuff in the interim / while I poke

2024-11-24 21:07 UTC, this-is-envy commented on Scripts/Components/Inventory/InventoryManager.gd
>  # Unsure if these will be used, placeholders
rm, we're using them now :D

2024-11-24 21:07 UTC, this-is-envy commented on Scripts/Components/Inventory/InventoryManager.gd
> +signal load_inventory
imo these are an inversion of expected usage and will make it difficult if we want to change how inventory is handled in the future

If we were going to use these as part of a signal bus (globally accessible) to indicate requested action then we would hang them off an autoload/global `SignalBus` class and correct to them in the `InventoryManager._ready`. Having them as a signal that InventoryManager owns suggests that it will be called when the inventory manager finishing saving its state as a outbound notification.

Some high points about how I'd structure this:

- It's already expected that we can walking up to driver and down to InventoryManager (and we're doing so anyway to emit save_inventory) so we might as well directly call `InventoryManager.save`
- Because we don't want to make InventoryManager understand how our save system works let's not have it understand how to actually write itself to disk
  - Instead let it generate either a data object that should get saved or a JSON string that captures its state; that probably changes the _save signature to : `save() -> String` and _load to `load(String) -> bool`
  - SerializationManager's save path now looks something like:

        func _save_game() -> void:
            print("Saving Game")
            if !_check_file_path_exists():
                _create_file_paths()
            
            var inv_data := Driver.instance().inventory_mgr.save()
            
            # Update meta data with last loaded level and non-level save data
            _write_meta_data(Driver.instance().update_loaded_level(), inv_data)
            
            _write_zip_file()
            DirAccess.rename_absolute(
                Utils.user_data_dir() + ZIP_FILE_NAME, Utils.user_data_dir() + SAVE_FILE_NAME
            )
            print("Saved Game")
- Ditch the InventoryManager save/load signals because they're no longer needed

2024-11-24 21:07 UTC, this-is-envy commented on Scripts/SerializationManager.gd
> +	get_parent().update_level.connect(_update_persistent_level)
You "should" be able to connect this through the UI. I had to disable "compatible methods only" which I found to be weird bc the signal and method match but idk 🤷 

![image](https://github.com/user-attachments/assets/93094b1b-4e31-4322-9f07-e14601f4fc21)

2024-11-24 21:07 UTC, this-is-envy commented on Scripts/Driver.gd
> +	_serialization_mgr.load_saved_level.connect(load_level)
same comment as update_level: this can be wired through the UI -- though here at least it understands that the methods are compatible

2024-11-24 21:07 UTC, this-is-envy commented on Scripts/Driver.gd
> +	if !autoload_scene_name.is_empty():
Right now if you have an autoload scene set running the game will load that scene in its raw form -- I can't quite tell if that's what we want but if we don't we should call `_serialization_mgr._load_game()` here.

I _think_ we probably do want to load saved state because the changes we'll be making won't always be fundamental "change the game flow" and as often as not could be map tweaks or whatever.

2024-11-24 21:07 UTC, this-is-envy commented on Scripts/Driver.gd
> +	_menu_mgr.show_menu(Enums.MenuType.SAVELOAD)
let's drop this into `_post_ready` -- at least for now we're not going to have a fully fleshed out save slot system and folks are likely to be loading directly into their levels to test so I expect we'll need pretty constant access to the debug menu

2024-11-24 21:07 UTC, this-is-envy commented on Scenes/Driver.tscn
> +[node name="SaveLoadMenu" type="Control" parent="OverlayManager/MenuManager"]
When this menu gets activated it takes focus and movement (left, right, etc) will move between buttons. Our interact key will also trigger button activation so playing the game will result in constantly futzing with the save state of the game.

I don't know off hand how to _not_ have that happen but if we can remove focus post-click (or make them un-focusable-but-still-clickable?) we should.

For a first cut / this PR it's fine to file as a ticket for follow up but we'll run into somebody deleting their save state or getting weird load in behavior before too long once folks are working on it.

2024-11-24 21:07 UTC, this-is-envy commented on Scripts/Driver.gd
>  	load_level(FIRST_LEVEL_NAME, LevelBase.DEFAULT_MARKER)
Since we no longer respect a _path passed in let's go ahead and change `ScratchScenes.gd` to not show things that can't be loaded rn, e.g., change SCENES to

```
const SCENES = {
	"Greyboxing": "res://ZZ_Scratch/GreyboxingTools/BadLevelA.tscn",
}
```

2024-11-24 21:07 UTC, this-is-envy commented on Scripts/Driver.gd
>  	load_level(FIRST_LEVEL_NAME, LevelBase.DEFAULT_MARKER)
Actually!

Utils.gd:
```
-const LEVEL_DIR := "res://ZZ_Scratch/GreyboxingTools/"
+const LEVEL_DIR := "res://Scenes/Levels/"
```

Driver.gd
```
-func request_debug_load(_path: String) -> void:
+func request_debug_load(name: String) -> void:
        var music_ready := audio_mgr.play(Enums.AudioTrack.SKETCH_2, 2)
        await _curtain.fade_in(1)
        _menu_mgr.hide_menu(Enums.MenuType.DEBUG)
        _menu_mgr.show_menu(Enums.MenuType.SAVELOAD)
        print("debug load")
-       load_level(FIRST_LEVEL_NAME, LevelBase.DEFAULT_MARKER)
+       load_level(name, LevelBase.DEFAULT_MARKER)
        await music_ready.finished
        await _curtain.fade_out(1)
```

ScratchScenes.gd
```
const SCENES = {
       "Greyboxing": "BadLevelA",
 }
```

and then (make sure to do this in the IDE/file inspector tab or a bunch of stuff will break) Drag BadLevelA & BadLevelB into `res://Scenes/Levels/` and we can start doing targeted loads again.

2024-11-24 21:07 UTC, this-is-envy commented on Scripts/Utils.gd
> +const LEVEL_DIR := "res://ZZ_Scratch/GreyboxingTools/"
see comment above on Driver.gd but let's go ahead and switch over to the thing now -- `res://Scenes/Levels`

2024-11-26 06:35 UTC, this-is-envy reviewed
I think the stuff that needs to get fixed pre-merge:

1. Get the HUD display call moved into _post_ready so that it's always available
2. Fix the ScratchScenes / _request_debug_load to work with any name instead of always defaulting to FIRST_LEVEL_NAME
3. Update the focus_mode attribute on the load/save buttons

Anything beyond that we can revisit in one or more focused changes

2024-11-26 06:35 UTC, this-is-envy commented on Scripts/Driver.gd
> +		new_level.setup(self)
More a thought than a change to make but we should consider passing a bool indicating if this is getting called on a first-visit. IDK what specifically a level might need that for but I can imagine some code that should run to get everything correctly configured which doesn't need to happen more than once.

An example would be like if it needs to add certain NPCs depending on the state of the world -- if it does that every time you'll have 2 NPCs if you re-run from a saved state etc.

2024-11-26 06:35 UTC, this-is-envy commented on Scenes/Driver.tscn
> +[node name="SaveLoadMenu" type="Control" parent="OverlayManager/MenuManager"]
Found it -- https://forum.godotengine.org/t/how-to-get-rid-of-the-button-focus-highlight/16415/3

Control > Input > Focus > Focus Mode = None

2024-11-26 06:35 UTC, this-is-envy commented on Scripts/Components/Inventory/InventoryManager.gd
> +signal load_inventory
Per our DMs let's kick this to the future so that we can focus on a couple of things to get merged; this works and we can always clean up in a follow up PR

2024-12-04 03:04 UTC, this-is-envy approved these changes
make it so!

we can set up time to walk through subsequent structural refactoring we might want to do / file bugs for it and any additional stuff we need to save (player location, inventory, quest states, etcetcetc)

2024-12-04 16:23 UTC, merged